INSERT INTO POSTS (POST_ID, PHOTO_ID, VIDEO_ID, USER_ID, LOCATION, USER_TAG, CAPTION) VALUES
(1, 5, NULL, 10, 'New York, USA', 'Alice Smith', 'A beautiful day in NYC!'),
(2, NULL, 15, 23, 'Los Angeles, USA', 'Michael Johnson', 'Sunset vibes in LA.'),
(3, 12, 22, 31, 'Paris, France', 'Sophie Martin', 'Bonjour from the Eiffel Tower!'),
(4, 8, NULL, 42, 'Tokyo, Japan', 'Hiroshi Tanaka', 'Cherry blossoms in Tokyo.'),
(5, NULL, 34, 56, 'London, UK', 'Emily Brown', 'Big Ben looks amazing today!'),
(6, 25, NULL, 63, 'Sydney, Australia', 'Liam Wilson', 'Opera House view.'),
(7, NULL, 41, 77, 'Berlin, Germany', 'Oliver Schmidt', 'Exploring Berlin streets!'),
(8, 18, 29, 88, 'Toronto, Canada', 'Emma White', 'Chilling at CN Tower.'),
(9, 30, NULL, 95, 'Dubai, UAE', 'Aisha Khalid', 'Burj Khalifa at night.'),
(10, NULL, 50, 102, 'Rio de Janeiro, Brazil', 'Carlos Mendes', 'Carnival time!'),
(11, 41, 15, 112, 'Rome, Italy', 'Giovanni Russo', 'The Colosseum is stunning!'),
(12, NULL, 61, 125, 'Barcelona, Spain', 'Miguel Garcia', 'La Sagrada Familia visit.'),
(13, 56, NULL, 133, 'Amsterdam, Netherlands', 'Anna De Vries', 'Cycling in Amsterdam.'),
(14, 66, 72, 140, 'Bangkok, Thailand', 'Narongchai Wong', 'Street food is delicious!'),
(15, NULL, 84, 150, 'Seoul, South Korea', 'Ji-Hoon Kim', 'Visiting Gyeongbokgung Palace!'),
(16, 21, NULL, 35, 'Mumbai, India', 'Rahul Verma', 'Marine Drive evening stroll.'),
(17, NULL, 49, 50, 'Cairo, Egypt', 'Ahmed Hassan', 'Pyramids are breathtaking!'),
(18, 37, 24, 75, 'Bali, Indonesia', 'Dewi Kartika', 'Relaxing on the beach.'),
(19, NULL, 77, 89, 'Singapore', 'Benjamin Tan', 'City skyline looks amazing!'),
(20, 52, NULL, 99, 'Istanbul, Turkey', 'Mehmet Kaya', 'Exploring the Grand Bazaar.'),
(21, NULL, 33, 115, 'San Francisco, USA', 'Jessica Lee', 'Golden Gate Bridge beauty.'),
(22, 45, 20, 127, 'Athens, Greece', 'Nikos Papadopoulos', 'Acropolis view!'),
(23, NULL, 38, 132, 'Cape Town, South Africa', 'Thabo Nkosi', 'Table Mountain hike.'),
(24, 60, NULL, 145, 'Hanoi, Vietnam', 'Nguyen Minh', 'Local street markets.'),
(25, NULL, 71, 148, 'Lisbon, Portugal', 'Francisco Silva', 'Pastel de nata cravings!'),
(26, 33, 18, 28, 'Moscow, Russia', 'Ivan Petrov', 'Red Square vibes.'),
(27, NULL, 40, 37, 'Kuala Lumpur, Malaysia', 'Mohd Faisal', 'Petronas Towers lit up!'),
(28, 20, 30, 55, 'Stockholm, Sweden', 'Elin Svensson', 'Gamla Stan beauty.'),
(29, NULL, 42, 74, 'Oslo, Norway', 'Lars Andersen', 'Exploring the fjords.'),
(30, 15, NULL, 83, 'Prague, Czech Republic', 'Jakub Novak', 'The Old Town charm.'),
(31, NULL, 63, 90, 'Budapest, Hungary', 'István Horváth', 'Danube River cruise.'),
(32, 12, 48, 102, 'Brussels, Belgium', 'Luc Dupont', 'Trying out Belgian waffles!'),
(33, NULL, 55, 118, 'Vienna, Austria', 'Johann Fischer', 'Schönbrunn Palace visit.'),
(34, 50, 14, 131, 'Dublin, Ireland', 'Sean O\'Connor', 'Cheers from the Guinness factory!'),
(35, NULL, 76, 146, 'Copenhagen, Denmark', 'Frederik Jensen', 'Nyhavn waterfront stroll.'),
(36, 44, NULL, 23, 'Mexico City, Mexico', 'Juan Pérez', 'Aztec ruins adventure!'),
(37, NULL, 39, 67, 'Jakarta, Indonesia', 'Budi Santoso', 'National Monument view.'),
(38, 58, NULL, 79, 'Buenos Aires, Argentina', 'Mateo Rodríguez', 'Tango in the streets.'),
(39, NULL, 66, 97, 'Lima, Peru', 'Ricardo Guzmán', 'Exploring Machu Picchu!'),
(40, 36, 9, 111, 'Hong Kong', 'Wang Wei', 'Victoria Peak sunset.'),
(41, NULL, 19, 121, 'Taipei, Taiwan', 'Chen Li', '101 Tower in the skyline!'),
(42, 29, 17, 139, 'Havana, Cuba', 'Javier Torres', 'Classic cars everywhere!'),
(43, NULL, 32, 144, 'Nairobi, Kenya', 'Samuel Otieno', 'Safari adventure.'),
(44, 64, 11, 149, 'Helsinki, Finland', 'Olli Mäkinen', 'Snowy landscapes.'),
(45, NULL, 22, 24, 'Reykjavik, Iceland', 'Björn Gunnarsson', 'Northern lights spotted!'),
(46, 55, NULL, 42, 'Warsaw, Poland', 'Mateusz Kowalski', 'Old Town charm.'),
(47, NULL, 80, 59, 'Edinburgh, Scotland', 'Fiona MacDonald', 'Castle on the hill.'),
(48, 43, 35, 70, 'Manila, Philippines', 'Jose Dela Cruz', 'Jeepney ride experience.'),
(49, NULL, 27, 87, 'New Delhi, India', 'Ananya Sharma', 'Qutub Minar standing tall!'),
(50, 61, 7, 98, 'Bogotá, Colombia', 'Andrés Castillo', 'Andes Mountains view.'),
(51, NULL, 90, 105, 'La Paz, Bolivia', 'Diego Fernández', 'High altitude cityscape.'),
(52, 49, NULL, 120, 'Santiago, Chile', 'Santiago Rojas', 'The Andes in the backdrop.'),
(53, NULL, 36, 133, 'Montevideo, Uruguay', 'Pablo Méndez', 'Sunset by the Rambla.'),
(54, 70, NULL, 142, 'Quito, Ecuador', 'Luis Herrera', 'Middle of the world!'),
(55, NULL, 26, 148, 'Casablanca, Morocco', 'Mohamed Idrissi', 'Hassan II Mosque beauty.'),
(56, NULL, 12, 21, 'Buenos Aires, Argentina', 'Carlos Mendoza', 'Enjoying a tango night!'),
(57, 32, NULL, 36, 'Madrid, Spain', 'Elena González', 'Exploring the Royal Palace!'),
(58, NULL, 45, 47, 'Zurich, Switzerland', 'Lukas Meier', 'Snowboarding in the Alps!'),
(59, 25, 9, 58, 'Beijing, China', 'Zhang Wei', 'Walking the Great Wall!'),
(60, NULL, 63, 66, 'Bangkok, Thailand', 'Somchai Rattanakorn', 'Floating market vibes!'),
(61, 44, NULL, 78, 'Vienna, Austria', 'Stefan Huber', 'Classical music concert!'),
(62, NULL, 31, 85, 'Berlin, Germany', 'Hans Müller', 'Checkpoint Charlie visit.'),
(63, 59, 18, 94, 'Cape Town, South Africa', 'Lebo Dlamini', 'Table Mountain sunrise!'),
(64, NULL, 75, 103, 'Toronto, Canada', 'Jessica Robinson', 'Skydiving over Niagara!'),
(65, 14, NULL, 115, 'Mumbai, India', 'Priya Desai', 'Gateway of India selfie!'),
(66, NULL, 37, 124, 'Kuala Lumpur, Malaysia', 'Ahmad Faisal', 'Petronas Towers at night!'),
(67, 40, 28, 131, 'Los Angeles, USA', 'David Thompson', 'Hollywood Boulevard walk!'),
(68, NULL, 50, 140, 'San Francisco, USA', 'Ethan Miller', 'Foggy morning at Golden Gate.'),
(69, 11, NULL, 145, 'Lisbon, Portugal', 'Pedro Almeida', 'Tram ride through Alfama!'),
(70, NULL, 69, 149, 'Athens, Greece', 'Nikos Karamanlis', 'Parthenon sunset view.'),
(71, 18, 35, 150, 'Hong Kong', 'Chen Ming', 'Dumpling feast in Mong Kok!'),
(72, NULL, 78, 29, 'Manila, Philippines', 'Miguel Santos', 'Sunset by Manila Bay!'),
(73, 23, NULL, 38, 'Jakarta, Indonesia', 'Siti Rahmawati', 'Batik shopping adventure!'),
(74, NULL, 44, 53, 'Dubai, UAE', 'Aisha Mohammed', 'Desert safari thrill!'),
(75, 34, 15, 61, 'Oslo, Norway', 'Anders Jensen', 'Northern Lights spotting!');

SELECT * FROM POSTS;