DROP DATABASE IF EXISTS XINST_SOCIAL_MEDIA;
CREATE DATABASE XINST_SOCIAL_MEDIA;
USE XINST_SOCIAL_MEDIA;

-- USERS TABLE
CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(50) UNIQUE NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    EMAIL_ID VARCHAR(50) UNIQUE NOT NULL,
    PROFILE_PHOTO VARCHAR(300),
    BIO_DATA VARCHAR(100) NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- LOGIN TABLE
CREATE TABLE LOGIN (
    LOGIN_ID INT AUTO_INCREMENT PRIMARY KEY,
    LOGIN_PASSWORD VARCHAR(50) NOT NULL,
    USER_ID INT NOT NULL UNIQUE, -- Ensures a user can have only one active login
    IP_ADDRESS VARCHAR(50) NOT NULL,
    LOGIN_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- PHOTOS TABLE
CREATE TABLE PHOTOS (
    PHOTO_ID INT AUTO_INCREMENT PRIMARY KEY,
    POST_ID INT NULL,
    PHOTO VARCHAR(300) NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PHOTO_SIZE FLOAT,
    CONSTRAINT CHK_PHOTO_SIZE CHECK (PHOTO_SIZE < 20)
);

-- REELS TABLE
DROP TABLE IF EXISTS REELS;
CREATE TABLE REELS (
    REEL_ID INT AUTO_INCREMENT PRIMARY KEY,
    POST_ID INT NULL,
    REEL VARCHAR(300) NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REEL_SIZE FLOAT,
    CONSTRAINT CHK_REEL_SIZE CHECK (REEL_SIZE < 20)
);

-- POSTS TABLE
CREATE TABLE POSTS (
    POST_ID INT AUTO_INCREMENT PRIMARY KEY,
    PHOTO_ID INT NULL,
    REEL_ID INT NULL,
    USER_ID INT NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LOCATION VARCHAR(300),
    USER_TAG VARCHAR(300),
    CAPTION VARCHAR(200) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (PHOTO_ID) REFERENCES PHOTOS(PHOTO_ID) ON DELETE SET NULL,
    FOREIGN KEY (REEL_ID) REFERENCES REELS(REEL_ID) ON DELETE SET NULL
);

-- COMMENTS TABLE
CREATE TABLE COMMENTS (
    COMMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    POST_ID INT NOT NULL,
    COMMENTS_ENTERED VARCHAR(200) NOT NULL,
    ENTERED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SUBMITTED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID)
);

-- POST LIKES TABLE
CREATE TABLE PHOTO_LIKES (
    PHOTO_LIKES_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    POST_ID INT NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID)
);

-- REEL LIKES TABLE
CREATE TABLE REEL_LIKES (
    REEL_LIKES_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    POST_ID INT NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID)
);

-- COMMENT LIKES TABLE
CREATE TABLE COMMENT_LIKES (
    COMMENT_LIKES_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    COMMENT_ID INT NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (COMMENT_ID) REFERENCES COMMENTS(COMMENT_ID)
);

-- FOLLOWS TABLE
CREATE TABLE FOLLOWS (
    FOLLOWER_ID INT NOT NULL,
    FOLLOWED_USER_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (FOLLOWER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (FOLLOWED_USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    PRIMARY KEY(FOLLOWER_ID, FOLLOWED_USER_ID)
);

-- HASHTAGS TABLE
CREATE TABLE HASHTAGS (
    HASHTAG_ID INT AUTO_INCREMENT PRIMARY KEY,
    HASHTAG_NAME VARCHAR(255) UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- HASHTAG FOLLOW TABLE
CREATE TABLE HASHTAG_FOLLOW (
    USER_ID INT NOT NULL,
    HASHTAG_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, HASHTAG_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (HASHTAG_ID) REFERENCES HASHTAGS(HASHTAG_ID)
);

-- POST TAGS TABLE
CREATE TABLE POST_TAGS (
	POST_TAGS_ID INT NOT NULL,
    POST_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    HASHTAG_ID INT NOT NULL,
    PRIMARY KEY (POST_TAGS_ID),
    FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (HASHTAG_ID) REFERENCES HASHTAGS(HASHTAG_ID)
);

-- BOOKMARKS TABLE
CREATE TABLE BOOKMARKS (
	BOOKMARKS_ID INT NOT NULL,
    POST_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (BOOKMARKS_ID,USER_ID, POST_ID),
    FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);
