-- Which users have posted the highest number of photos and reels combined? 
-- List the top 5 with their usernames and post counts.

SELECT U.USER_NAME USER_NAME, COUNT(P.POST_ID) POST_COUNT 
FROM USERS U 
JOIN POSTS P ON P.USER_ID = U.USER_ID
WHERE P.PHOTO_ID IS NOT NULL OR P.REEL_ID IS NOT NULL
GROUP BY P.USER_ID
ORDER BY POST_COUNT DESC LIMIT 5;


--  Identify posts that have more comments, more likes, and more bookmarks (high engagement posts).
SELECT DISTINCT(P.POST_ID) POST_IDS, 
	    COUNT(P.POST_ID) POST_COUNT 
FROM POSTS P
LEFT JOIN COMMENTS C ON P.POST_ID = C.POST_ID
LEFT JOIN PHOTO_LIKES PL ON P.POST_ID = PL.POST_ID
LEFT JOIN REEL_LIKES RL ON P.POST_ID = RL.POST_ID
LEFT JOIN BOOKMARKS B ON P.POST_ID = B.POST_ID
WHERE C.COMMENT_ID IS NOT NULL AND 
	  PL.PHOTO_LIKES_ID IS NOT NULL AND
      RL.REEL_LIKES_ID IS NOT NULL AND
      B.BOOKMARKS_ID IS NOT NULL
GROUP BY POST_IDS LIMIT 10;


-- Are there users who have logged in from more than 1 different IP addresses in a single day if nothing captured then show 10 IP entries? 
-- If so, list those users and IPs.

SELECT U.USER_ID USER_ID,
	U.USER_NAME USER_NAME, 
	DATE(L.LOGIN_TIME) LOGIN_DATE,
	COUNT(DISTINCT IP_ADDRESS) UNIQUE_IPS
FROM USERS U
LEFT JOIN LOGIN L ON L.USER_ID = U.USER_ID
GROUP BY USER_ID, LOGIN_DATE
HAVING UNIQUE_IPS>0
LIMIT 10;

-- Show all users who follow at other users.
-- Identify count of all users who have commented on a post but haven’t liked it.

SELECT FOLLOWER_ID, 
	   COUNT(*) FOLLOWING_COUNT
FROM FOLLOWS
GROUP BY FOLLOWER_ID
HAVING COUNT(*) >=1 
LIMIT 5;

SELECT COUNT(DISTINCT C.USER_ID) USER_COUNTS
FROM COMMENTS C
LEFT JOIN PHOTO_LIKES PL 
	   ON C.USER_ID = PL.USER_ID 
	  AND C.POST_ID = PL.POST_ID
WHERE PL.USER_ID IS NULL;

-- Display the most active user based on total likes (photo + reel) they’ve given.

SELECT USER_ID, COUNT(*) TOTAL_LIKES
FROM (
		SELECT USER_ID FROM PHOTO_LIKES
		UNION ALL 
		SELECT USER_ID FROM REEL_LIKES
) AS ALL_LIKES
GROUP BY USER_ID
ORDER BY TOTAL_LIKES DESC
LIMIT 10;


SELECT 
    USER_ID, 
    MEDIA_TYPE,
    COUNT(*) AS TOTAL_LIKES
FROM (
    SELECT USER_ID, 'Photo' AS MEDIA_TYPE
    FROM PHOTO_LIKES
    UNION ALL
    SELECT USER_ID, 'Reel' AS MEDIA_TYPE
    FROM REEL_LIKES
) AS ALL_LIKES
GROUP BY USER_ID, MEDIA_TYPE
ORDER BY TOTAL_LIKES DESC
LIMIT 10;

-- Find users who have more than 1000 followers but haven't posted anything in the last 60 days.

SELECT 
    U.USER_ID,
    U.USER_NAME,
    COUNT(F.USER_ID) AS FOLLOWERS_COUNT
FROM USERS U
LEFT JOIN FOLLOWS F ON U.USER_ID = F.FOLLOWED_USER_ID
WHERE U.USER_ID NOT IN (
    SELECT DISTINCT USER_ID
    FROM POSTS
    WHERE CREATED_TIME >= NOW() - INTERVAL 60 DAY
)
GROUP BY U.USER_ID, U.USER_NAME
HAVING FOLLOWERS_COUNT > 1000
ORDER BY FOLLOWERS_COUNT DESC;

-- Which location (city) has the highest number of posts, and what's the average number of likes per post in that city?
-- OUTPUT
SELECT 
    P.LOCATION,
    COUNT(P.POST_ID) AS POST_COUNT,
    AVG(COALESCE(PL_LIKES.LIKES, 0) + COALESCE(RL_LIKES.LIKES, 0)) AS AVG_TOTAL_LIKES
FROM POSTS P
LEFT JOIN (
    SELECT POST_ID, COUNT(PHOTO_LIKES_ID) AS LIKES
    FROM PHOTO_LIKES
    GROUP BY POST_ID
) PL_LIKES ON P.POST_ID = PL_LIKES.POST_ID
LEFT JOIN (
    SELECT POST_ID, COUNT(REEL_LIKES_ID) AS LIKES
    FROM REEL_LIKES
    GROUP BY POST_ID
) RL_LIKES ON P.POST_ID = RL_LIKES.POST_ID
GROUP BY P.LOCATION
ORDER BY AVG_TOTAL_LIKES DESC
LIMIT 1;

-- Which location (city) has the highest number of posts, and what's the average number of likes per post in that city?
WITH CITYPOSTS AS (
    SELECT LOCATION, COUNT(*) AS TOTAL_POSTS
    FROM POSTS GROUP BY LOCATION
),
CITYLIKES AS (
    SELECT 
        P.LOCATION,
        COUNT(PL.PHOTO_LIKES_ID) + COUNT(RL.REEL_LIKES_ID) AS TOTAL_LIKES,
        COUNT(DISTINCT P.POST_ID) AS TOTAL_POSTS
    FROM POSTS P
    LEFT JOIN PHOTO_LIKES PL ON P.POST_ID = PL.POST_ID
    LEFT JOIN REEL_LIKES RL ON P.POST_ID = RL.POST_ID
    GROUP BY P.LOCATION
),
TopCity AS (
    SELECT LOCATION FROM CITYPOSTS
    ORDER BY TOTAL_POSTS DESC LIMIT 1
)
SELECT 
    CL.LOCATION, CP.TOTAL_POSTS,
    (CL.TOTAL_LIKES * 1.0 / CP.TOTAL_POSTS) AS AVERAGE_LIKES_PER_POST
FROM TopCity TC
JOIN CITYPOSTS CP ON TC.LOCATION = CP.LOCATION
JOIN CITYLIKES CL ON TC.LOCATION = CL.LOCATION;

-- Find top 10 users who posted a photo and received a comment or like within 5 minutes of posting. 
SELECT DISTINCT P.USER_ID, P.POST_ID, P.CREATED_TIME AS POST_TIME, 
       PL.CREATED_TIME AS LIKE_TIME, PC.SUBMITTED_TIME AS COMMENT_TIME
FROM POSTS P
LEFT JOIN PHOTO_LIKES PL ON P.POST_ID = PL.POST_ID
LEFT JOIN COMMENTS PC ON P.POST_ID = PC.POST_ID
WHERE (
    (PL.CREATED_TIME IS NOT NULL AND TIMESTAMPDIFF(MINUTE, P.CREATED_TIME, PL.CREATED_TIME) <= 5)
    OR
    (PC.SUBMITTED_TIME IS NOT NULL AND TIMESTAMPDIFF(MINUTE, P.CREATED_TIME, PC.SUBMITTED_TIME) <= 5)
)
AND P.PHOTO_ID IS NOT NULL
LIMIT 10;  -- Only photos, not reels






